### ISSUE TITLE
Data loaded in Fuseki

### ISSUE THREAD

**Issue by emir-munoz** [Claudenw/galway2020#5]
I have found triples with two duplicate predicates URL, where in the first predicate the "#" symbol is missing.

1) <http://www.geonames.org/ontologycountryCode>
<http://www.geonames.org/ontology#countryCode>

2) <http://www.geonames.org/ontologyname>
<http://www.geonames.org/ontology#name>

**Comment by Claudenw** [comment]
Yes, there was an earlier issue with the namespace.  It should be fixed in newer data

**Comment by Claudenw** [comment]
All data has been reloaded.  And the data corrected

**Comment by emir-munoz** [comment]
Great, thanks Claude
